[package]
name = "tauri-plugin-python"
version = "0.0.0"
authors = ["Olivier Lemasle"]
description = ""
edition = "2021"
rust-version = "1.70"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]

[dependencies]
tauri = { version = "2.0.0-alpha.21" }
serde = "1.0"
thiserror = "1.0"
