name: Format and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install rustfmt with stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.75.0"
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check format for plugin
        run: cargo fmt --all -- --check

      - name: Check format for example
        run: cargo fmt --manifest-path=examples/tauri-app/src-tauri/Cargo.toml --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1

      - name: Install clippy with stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.75.0"
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
