name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install rustfmt with stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check format for plugin
        run: cargo fmt --all -- --check

      - name: Check format for example
        run: cargo fmt --manifest-path=examples/tauri-app/src-tauri/Cargo.toml --all -- --check
